server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://rm-2zexhq7yo56a0z37wgo.mysql.rds.aliyuncs.com:3306/naruto?serverTimezone=GMT&characterEncoding=utf-8
    data-username: zhangdong
    data-password: Bageling0
    driver-class-name: com.mysql.cj.jdbc.Driver
  #设置静态文件路径，js，css等
  mvc:
    static-path-pattern: /static/**
  # freemarker 静态资源配置
  freemarker:
    #设定ftl文件路径
    template-loader-path: classpath:/templates
    # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

# thymeleaf 静态资源配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false



#热部署生效
#  devtools:
#    restart:
#      enabled: true
#设置热部署重启的目录
#      additional-paths: src/main/java

mybatis:
  mapper-locations: classpath:mapper/*.xml

redis:
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password: 123456
  lettuce:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
  # 连接超时时间（毫秒）
  timeout: 1000
