server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT&characterEncoding=utf-8
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

#关闭缓存，及时刷新

#  thymeleaf:
#    cache: true
#
#热部署生效
#  devtools:
#    restart:
#      enabled: true
#设置热部署重启的目录
#      additional-paths: src/main/java

mybatis:
  mapper-locations: classpath:mapper/*.xml
